### PR TITLE
Serialization of relative URI

### PR DESCRIPTION
**Pull request by DavidDeSloovere**
For now just adding tests to trigger the same exception I get in my code.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/VerifyTests/Verify?pullRequest=374) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/VerifyTests/Verify?pullRequest=374) before we can accept your contribution.<br/><br/>:x: DavidDeSloovere [sign now](https://cla.dotnetfoundation.org/VerifyTests/Verify?pullRequest=374)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/VerifyTests/Verify?pullRequest=374) it.</sub>

**Comment by DavidDeSloovere** [comment]
I still need to install not only .NET FW 4.8 but also .NET 6 on my machine. But wanted to get this out earlier.

**Comment by SimonCropp** [comment]
leave it with me.

**Comment by DavidDeSloovere** [comment]
I actually just fixed it.

`Query` property is not available for relative urls

```
public override void WriteJson(
        JsonWriter writer,
        Uri value,
        JsonSerializer serializer,
        IReadOnlyDictionary<string, object> context)
    {
        if (value.IsAbsoluteUri == false)
        {
            writer.WriteValue(value.OriginalString);
            return;
        }

        if (string.IsNullOrWhiteSpace(value.Query))
        {
            writer.WriteValue(value.OriginalString);
            return;
        }

        var path = GetPath(value);

        serializer.Serialize(writer,
            new UriWrapper
            {
                Path = path,
                Query = HttpUtility.ParseQueryString(value.Query)
            });
    }
```

**Pull request merged**
