### PR TITLE
Add unique for architecture

### PR DESCRIPTION
**Pull request by andrewlock**
In some (admittedly rare) cases, the output may be different between platforms (I found this specifically recently) where stack traces were different between platforms. Hope this good to you!

### CODE REVIEW

**Comment by SimonCropp** [comment]
too many conflicts. so i did a new PR with your changes and gave u credit on the commit.

**Comment by andrewlock** [comment]
No worries, thanks!

**Comment by SimonCropp** [comment]
this is now deployed

**Comment by andrewlock** [comment]
Wow, that's fast, thanks! 🎉😀

**Pull request closed without merging**
