### PR TITLE
Don't reference System.IO.Compression package

### PR DESCRIPTION
**Pull request by ViktorHofer**
System.IO.Compression is inbox on .NET Framework. The package doesn't need to be referenced and will eventually be marked as deprecated.

image

I also cleaned-up the project files as they were hard to read. I hope that's OK.

### CODE REVIEW

**Comment by SimonCropp** [comment]
the broken build would imply that it is required 
```
C:\projects\verify\src\Verify.NUnit\Verifier_Archive.cs(12,9): error CS0246: The type or namespace name 'ZipArchive' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\verify\src\Verify.NUnit\Verify.NUnit.csproj::TargetFramework=net472]
C:\projects\verify\src\Verify.NUnit\Verifier_Archive.cs(13,14): error CS0246: The type or namespace name 'ZipArchiveEntry' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\verify\src\Verify.NUnit\Verify.NUnit.csproj::TargetFramework=net472]
C:\projects\verify\src\Verify.NUnit\VerifyBase_Archive.cs(12,9): error CS0246: The type or namespace name 'ZipArchive' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\verify\src\Verify.NUnit\Verify.NUnit.csproj::TargetFramework=net472]
C:\projects\verify\src\Verify.NUnit\VerifyBase_Archive.cs(13,14): error CS0246: The type or namespace name 'ZipArchiveEntry' could not be found (are you missing a using directive or an assembly reference?) 
```

**Review by akoeplinger — APPROVED** [review]

**Comment by ViktorHofer** [comment]
> the broken build would imply that it is required

PackageReferences flow transitively to consuming projects while `<Reference />` items do not. I had to add the reference item to all the projects that use the Compression API. The package isn't required because System.IO.Compression.dll is part of the .NET Framework installation and just needs to be referenced explicitly.

**Comment by ViktorHofer** [comment]
The PR is now ready :)

**Comment by SimonCropp** [comment]
@ViktorHofer thanks

**Comment by SimonCropp** [comment]
i will deploy this now

**Pull request merged**
