### PR TITLE
Undo removal of 'Verifier.' in docs

### PR DESCRIPTION
**Pull request by Siphonophora**
Hey, looks like find replace in 41e5e4f086fe668e9b480a2ca553cfb9af02abc1 broke the example docs.

### CODE REVIEW

**Comment by Siphonophora** [comment]
Oh, I just noticed all the markdown is being built from those snippets. So maybe there just needs to be a comment on the readme next to the one about implicit usings.

**Comment by SimonCropp** [comment]
you mean this comment? https://github.com/VerifyTests/Verify#usage

> All examples use [ImplicitUsings](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#implicitusings). Ensure the following is set to have examples compile correctly <ImplicitUsings>enable</ImplicitUsings>

**Comment by Siphonophora** [comment]
Yeah. A comment there that you are expecting the static using would make sense.

**Comment by SimonCropp** [comment]
there is already a comment

**Pull request closed without merging**
