### PR TITLE
Do not create artifical name for extension-only filenames

### PR DESCRIPTION
**Pull request by JanKrivanek**
### Problem
Verification of files that starts with dot (e.g. `.editorconfig`) generates/uses snapshots which prepend `nofilename` to the tested file. This is a minor inconvenience - discussed here: https://github.com/VerifyTests/Verify/issues/699#issuecomment-1302881371

### Solution
filename is preserved as empty
directory structure is preserved as well
appropriate tests added

### Note
Potentially similar approach might be taken for files without extensions (currently artifical `.noextension` extension appended). This would require some changes in `EmptyFiles` as well (to support empty extension). I'm leaving it for separate work if it ever becomes concern for anyone.

### CODE REVIEW

**Comment by JanKrivanek** [comment]
> so this is a breaking change?

That's correct.
More precisely:
* For updates from >= 18.3.1-beta.1 it's breaking
* For updates from <= 18.3.0 it's actualy enabling the upgrade *without* the breaking change that's currently imposed (as previously the 'dot filename' that was contained within some subdirectory was supported as is and in newer version the snapshot name is altered)

We are currently in the second category (trying to prevent sequence of 2 breaking changes)

**Comment by SimonCropp** [comment]
do u think it makes sense for this to handle deletion of the legacy file?

if no can u add a section in the description for how people can manually clean up

**Comment by JanKrivanek** [comment]
Good point.
Will look into that and update.

**Comment by JanKrivanek** [comment]
@SimonCropp I update the PR to rename the snapshots from previous naming convention (simple cleanup of previous naming convention is in previous commit - if that feels as better strategy). Let me know what are your thoughts on that.
Thanks!

**Pull request merged**
