### PR TITLE
Test for TreatAsString

### PR DESCRIPTION
**Pull request by HEskandari**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/VerifyTests/Verify?pullRequest=189) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/VerifyTests/Verify?pullRequest=189) before we can accept your contribution.<br/><br/>:x: HEskandari [sign now](https://cla.dotnetfoundation.org/VerifyTests/Verify?pullRequest=189)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/VerifyTests/Verify?pullRequest=189) it.</sub>

**Comment by HEskandari** [comment]
@SimonCropp this is the failing test. I have added the approved result to show what I expected.

**Comment by SimonCropp** [comment]
TreatAsString is only built to work with root types being based in.

> Certain types, **when passed directly in to Verify**, are written directly without going through json serialization

https://github.com/VerifyTests/Verify/blob/master/docs/serializer-settings.md#treatasstring

If you want to control serialization at the json level you need to tweak the json.net config https://github.com/VerifyTests/Verify/blob/master/docs/serializer-settings.md#changing-jsonnet-settings
eg by adding a custom converter https://www.newtonsoft.com/json/help/html/CustomJsonConverter.htm

**Comment by HEskandari** [comment]
Closing this for now.

**Pull request closed without merging**
