### PR TITLE
fix: Issue with report with Linux file paths when updating from 23.7.1 to 23.7.2

### LINKED ISSUE #1196: Issue with report with Linux file paths when updating from 23.7.1 to 23.7.2
Hello,

Updating from 23.7.1 to 23.7.2 is breaking my CI.  I'm building my application on a Windows machine and executing the tests on a Linux one.

In the CI log we can see:

```
VerifyException : Directory: D:\b\0\2091\Source\Macros\Tests\Source\Scripting/D:\b\0\2091\Source\Macros\Tests\Source\Scripting
New:
  - Received: D:\b\0\2091\Source\Macros\Tests\Source\Scripting/D:\b\0\2091\Source\Macros\Tests\Source\Scripting/Test_Generate_Project_Is_Deterministic.net60.LINUX.DotNet6_0.received.txt
    Verified: D:\b\0\2091\Source\Macros\Tests\Source\Scripting/D:\b\0\2091\Source\Macros\Tests\Source\Scripting/Test_Generate_Project_Is_Deterministic.net60.LINUX.verified.txt
```

When looking closely we can see that the path is concatenated twice:

`D:\b\0\2091\Source\Macros\Tests\Source\Scripting/D:\b\0\2091\Source\Macros\Tests\Source\Scripting/`

The settings are set like that:

```csharp
        private VerifySettings GetVerifySettings([CallerMemberName] string methodName = null)
        {
            var settings = new VerifySettings();
            settings.DisableRequireUniquePrefix();

            string fileName;
#if NET472
            fileName = $"{methodName}.net472";
#else
            fileName = $"{methodName}.net60";
#endif
            if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
                fileName += ".OSX";
            else if (!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
                fileName += ".LINUX";

            settings.UseFileName(fileName);
            return settings;
        }
```

I quickly looked at the [diff](https://github.com/VerifyTests/Verify/compare/23.7.1...23.7.2) and I can see some changes regarding path concatenation that might explain the regression.

(the issue is also present with version 24.1.0)

### PR DESCRIPTION
**Pull request by jairbubbles**
- Closes #1196

### CODE REVIEW

**Comment by jairbubbles** [comment]
@SimonCropp I didn't really how to test the exact flow so I swapped locally compiled .dll and execute on WSL. It seems that reintroducing the replace remove in your commit https://github.com/VerifyTests/Verify/commit/7dc99a99c68ada715e9429062d640574ed60548a was fixing the issue.

**Comment by jairbubbles** [comment]
@SimonCropp Yes I'll add a test.

**Comment by jairbubbles** [comment]
@SimonCropp I ended up doing more changes, I fee like it doesn't make much sense to use `Path.Combine` as we're mixing Linux and Windows paths. As a result, the code is less platform dependent.

**Comment by SimonCropp** [comment]
any updates on some tests in this one?

**Comment by jairbubbles** [comment]
Hi @SimonCropp, in fact it doesn't need a new test case. This case (build on windows and run on linux) was already covered but the test by itself was not properly detecting the issue because of the mocking .

**Comment by SimonCropp** [comment]
@jairbubbles thanks for the clarification. will ship this one now

**Pull request merged**
