### PR TITLE
Fix typo in method documentation for UseParameters()

### PR DESCRIPTION
**Pull request by elnigno**
Fix typo in method documentation for UseParameters()

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/VerifyTests/Verify?pullRequest=359) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/VerifyTests/Verify?pullRequest=359) before we can accept your contribution.<br/><br/>:x: elnigno [sign now](https://cla.dotnetfoundation.org/VerifyTests/Verify?pullRequest=359)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/VerifyTests/Verify?pullRequest=359) it.</sub>

**Comment by SimonCropp** [comment]
thanks

**Comment by elnigno** [comment]
No problem, thanks to you for Verify!

**Comment by SimonCropp** [comment]
no worries. A couple of questions

 * are you using diffenginetray to track pending snapshots? https://github.com/VerifyTests/DiffEngine/blob/master/docs/tray.md
 * if u dont mind me asking, what is your tech stack?

**Comment by elnigno** [comment]
- I wasn't aware about the tray but I will certainly try it, it looks like it can save me some time verifying many snapshots.
- ASP.NET Core, I'm trying our Verify as a tool do spot regressions in a Web API.

**Comment by SimonCropp** [comment]
ok. re web api https://github.com/VerifyTests/Verify.Web

**Pull request merged**
