### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by taspeotis**
I was searching for a way to compare XLSX files, but a cursory CTRL+F did not return any results in the README. There are two results, but they have typos in their listing.

### CODE REVIEW

**Comment by taspeotis** [comment]
@dotnet-policy-service agree

**Comment by SimonCropp** [comment]
thanks. and sorry for the hassle

**Comment by taspeotis** [comment]
No apology necessary! Thank you for maintaining this project.

**Comment by SimonCropp** [comment]
@taspeotis side question: what approach are you using for Snapshot management? https://github.com/VerifyTests/Verify?tab=readme-ov-file#snapshot-management

**Comment by taspeotis** [comment]
Of course, hopefully I understand the question correctly:

I have only just started using Verify in earnest so what can be done is new to me. For now I am renaming the files in the file system. I did encounter that section the readme while searching for ways to compare Excel files, and it  gave me two new avenues to explore:

* Merging the changes from `received` into `verified` via the diff tool (when it's text)
* The Rider extension

**Comment by SimonCropp** [comment]
> For now I am renaming the files in the file system

yeah thats a pain. r u on windows or mac?

**Comment by taspeotis** [comment]
Windows. For what it's worth it hasn't been too bad - using Rider I'd delete the verified. file and then CTRL+R, R rename the received to verified. But the README pointed to the Rider plugin, which I just tried, and it works.

**Comment by SimonCropp** [comment]
give DiffEngineTray a go https://github.com/VerifyTests/DiffEngine/blob/main/docs/tray.md

**Pull request merged**
