### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by Mahmooddlshad**
Verify

### CODE REVIEW

**Comment by Mahmooddlshad** [comment]
Berify

**Comment by Mahmooddlshad** [comment]
Verify

**Comment by Mahmooddlshad** [comment]
Hi

**Comment by Mahmooddlshad** [comment]
mahmooddlshad:patch-1

**Comment by Mahmooddlshad** [comment]
mahmooddlshad:patch-1

**Comment by SimonCropp** [comment]
can u add a description

**Pull request closed without merging**
