### PR TITLE
Adding parameter hashing function

### PR DESCRIPTION
**Pull request by aaronpowell**
This addresses the feature in #884

### CODE REVIEW

**Comment by SimonCropp** [comment]
can u add some docs

**Comment by aaronpowell** [comment]
> can u add some docs

Docs added with sample snippet.

**Comment by SimonCropp** [comment]
@aaronpowell did u end up using this feature?

**Comment by aaronpowell** [comment]
I'd assume so, but I don't know if it's still in use

**Comment by SimonCropp** [comment]
@aaronpowell can u check? context https://github.com/VerifyTests/Verify/pull/1449

if u still have a use case, i would like to dive deaper into it to work out if there is a better way to support it. or, if not, i might pull out the hashing to a diff nuget so it can move forward with the supported runtime of System.IO.Hashing

**Pull request merged**
