### PR TITLE
Allow user to sort serialized properties alphabetically

### PR DESCRIPTION
**Pull request by bmueller84**
As discussed in [this issue](https://github.com/VerifyTests/Verify/issues/396#issuecomment-915913731), I think it's useful to allow the user to enforce a consistent, alphabetical ordering of properties in the serialized data. A simple scenario that comes to mind is reordering members within a class, which would currently cause all corresponding tests to fail.

I've started with the most simple way to implement this (including a few tests). Please let me know what's missing.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/VerifyTests/Verify?pullRequest=398) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/VerifyTests/Verify?pullRequest=398) before we can accept your contribution.<br/><br/>:x: bmueller84 [sign now](https://cla.dotnetfoundation.org/VerifyTests/Verify?pullRequest=398)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/VerifyTests/Verify?pullRequest=398) it.</sub>

**Comment by SimonCropp** [comment]
i was assuming you would want this to be a single static config option?

**Comment by bmueller84** [comment]
Well, for versions before C# 9, we don't have module initializers, so each test class would have to to set this static config option anyway. But I guess it's not a bad idea to support both use cases. What do you think?

**Comment by SimonCropp** [comment]
while some cant use module initializers, you can still use a test startup in xunit/nunit/mstest. or u can use a static contractor in a test base class. i just dont see it bein required at the per-test level

**Comment by bmueller84** [comment]
I don't like these static settings general because they often make things harder to test. But it's your library, so I'm not gonna argue with you ;) How do you like the updated pull request?

Btw: NamerTests.ThrowOnConflict seems to be flaky (even on the original repo)

**Pull request merged**
