### PR TITLE
Add `Verify(Func<Task<T>>)`

### PR DESCRIPTION
**Pull request by dahlbyk**
A few times now we've wanted to make a helper like this, returning `SettingsTask` so we can `UseParameters()` or whatever:

```csharp
static SettingsTask VerifyFoo(Foo foo, BarRepo bars) =>
    Verify(new
    {
        foo,
        bar = await bars.GetBars(foo), // requires async!
    });
```

But the `await` requires `async Task<SettingsTask>` which then requires `await await VerifyFoo(...)`. Not pretty.

Accepting `Func<Task<T>>` makes building async targets much cleaner:

```csharp
static SettingsTask VerifyFoo(Foo foo, BarRepo bars) =>
    Verify(async () => new
    {
        foo,
        bar = await bars.GetBars(foo),
    });
```

### CODE REVIEW

**Comment by SimonCropp** [comment]
can you add some docs for this scenario

**Comment by dahlbyk** [comment]
> can you add some docs for this scenario

Added an **Async** section before **JsonVerify**.

**Comment by dahlbyk** [comment]
I guess I could also explicitly document the pattern one wants to wrap a `Verify()` call in a helper method like we did. Thoughts?

**Comment by SimonCropp** [comment]
> I guess I could also explicitly document the pattern one wants to wrap a Verify() call in a helper method like we did. 

i dont think it is necessary. 

i will merge and deploy this now.

sorry for the delay

**Comment by dahlbyk** [comment]
> sorry for the delay

No worries at all. Thanks for the library!

**Pull request merged**
