### PR TITLE
Fixing #491

### PR DESCRIPTION
**Pull request by tom-englert**
Fixing #491

### CODE REVIEW

**Comment by SimonCropp** [comment]
these tests seem to fail when running locally 

```
Xunit.Sdk.EqualException
Assert.Equal() Failure
Expected: List<String> ["00.received.txt", "00.verified.txt", "01.received.abc", "01.verified.abc"]
Actual:   List<String> ["00.received.txt", "00.verified.txt", "01.received.abc"]
   at StreamTests.VerifyFailsCorrectly_NoFilesExist() in C:\Code\VerifyTests\Verify\src\Verify.Tests\StreamTests\StreamTests.cs:line 57
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 265
--- End of stack trace from previous location where exception was thrown ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 49
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 91

```

**Comment by SimonCropp** [comment]
they also incorrectly show a diff tool for the txt file 
image

**Comment by SimonCropp** [comment]
actually the above stack trace is after i tried to fix it. the stack trace before my changes is 

```
Xunit.Sdk.EqualException
Assert.Equal() Failure
Expected: WhereArrayIterator<String> ["00.received.txt", "00.verified.txt", "01.received.abc", "01.verified.abc"]
Actual:   OrderedEnumerable<String, String> ["00.received.txt", "00.verified.txt", "01.received.abc"]
   at StreamTests.VerifyFailsCorrectly_NoFilesExist() in C:\Code\VerifyTests\Verify\src\Verify.Tests\StreamTests\StreamTests.cs:line 57
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location where exception was thrown ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
```

**Comment by tom-englert** [comment]
On my machine they run fine. They run the registered diff tool for all types, `since`suppportsText=true:
https://github.com/VerifyTests/Verify/blob/07ff728c2629cc51db9b63054c9f91cf427b200e/src/Verify.Tests/StreamTests/StreamTests.cs#L16-L21

**Comment by tom-englert** [comment]
If it runs a different comparer, of course the tests will fail...

**Comment by tom-englert** [comment]
I'm running VS2022 (17.1.0) on Win10 - I did not test is on other platforms.

**Comment by SimonCropp** [comment]
found the issue. this is now deployed

**Pull request merged**
