### PR TITLE
Source Generator - Hint Name

### PR DESCRIPTION
**Pull request by mrkwllce**
Extended the API to allow for passing along a hintName from Source Generators to allow the generator to use the existing unique name, so that the generated files will always be compared correctly.

### CODE REVIEW

**Comment by SimonCropp** [comment]
> so that the generated files will always be compared correctly.

can you give me some scenarios where files are not correctly compared

**Comment by mrkwllce** [comment]
Here's a branch that gives the example.

https://github.com/mrkwllce/Verify.SourceGenerators/tree/SampleBranch

**Comment by SimonCropp** [comment]
i changes it so it sorts by hintname https://github.com/VerifyTests/Verify.SourceGenerators/pull/60

do this fix you issue?

**Comment by SimonCropp** [comment]
can you try Verify.SourceGenerators 1.5.0-beta.1

**Pull request closed without merging**
