### PR TITLE
feat: added custom counter comparers

### PR DESCRIPTION
**Pull request by JaktensTid**
Ability to add custom comparers to Counter

```csharp
private class StubGuidComparer : IEqualityComparer<Guid>
    {
        public bool Equals(Guid x, Guid y) => true;

        public int GetHashCode(Guid obj) => 1;
    }

    [Fact]
    public async Task ShouldInjectCustomGuidComparer()
    {
        var obj = new
        {
            Item1 = Guid.NewGuid(),
            Item2 = Guid.NewGuid(),
            Item3 = Guid.NewGuid()
        };

        var settings = new VerifySettings();
        settings.ReplaceScrubberGuidComparer(new StubGuidComparer());
        await Verify(obj, settings: settings);
    }
```

This test case will produce the following .verified.txt file

```
{
  Item1: Guid_1,
  Item2: Guid_1,
  Item3: Guid_1
}
```

### CODE REVIEW

**Comment by JaktensTid** [comment]
@dotnet-policy-service agree

**Comment by SimonCropp** [comment]
can u explain why?

**Comment by JaktensTid** [comment]
@SimonCropp https://github.com/VerifyTests/Verify/issues/1285

**Comment by SimonCropp** [comment]
can u add some documentation that explains the use case with your datetime scenario

**Comment by JaktensTid** [comment]
@SimonCropp added

**Comment by SimonCropp** [comment]
do you need this to be a "per test" based feature? or would a static setting suffice?

**Comment by JaktensTid** [comment]
> do you need this to be a "per test" based feature? or would a static setting suffice?

Hi, it's more static setting

**Comment by JaktensTid** [comment]
@SimonCropp if there is ability to add it 'dynamic' let me know

**Comment by SimonCropp** [comment]
in that case how about you convert this PR to only be a static setting.

then i will merge and release it

**Comment by JaktensTid** [comment]
@SimonCropp you mean just make these settings 'static'?

**Pull request closed without merging**
